### ISSUE TITLE
Can't log in with Google account

### ISSUE THREAD

**Issue by Nossarian** [Blacksmoke16/GESI#57] opened 2020-02-19 16:34 UTC
Can't log in with Google account. This is preventing users from adding GESI as an add-on to Google Sheets.

**Comment by Blacksmoke16** [comment] 2020-02-19 16:35
Duplicate of #54

**Comment by Nossarian** [comment] 2020-02-19 16:35
Closed as dupe, though I recommend leaving issues open until they're resolved.

**Closed** 2020-02-19 16:35 UTC

**Comment by Blacksmoke16** [comment] 2020-03-08 16:06
This is resolved.
