### ISSUE TITLE
Error: {"error":"authentication failure"} (line 254)

### ISSUE THREAD

**Issue by d44644** [Blacksmoke16/GESI#113] opened 2024-01-29 18:09 UTC
I'm having trouble with getting just one of characters to work. All other dozen or so characters work just fine. But one returns "Error: {"error":"authentication failure"} (line 254) every time. It is authenticated and shows up when I do the getAuthenticatedCharacterNames() function. Tried resetting using different sheets same problem.

**Comment by d44644** [comment] 2024-02-16 01:48
I did some more testing and may have found the issue. I noticed that this one character that won't work has a really long name like the max the game will let you use. I made a new character with the most amount of characters in its name and it gives the same error.

**Comment by Blacksmoke16** [comment] 2024-02-16 02:05
@d44644 That's good information. What happens if you try authing directly on https://esi.evetech.net/ui/ and interacting with one of the endpoints?

**Comment by d44644** [comment] 2024-02-16 03:10
Everything seems to work fine. These characters work on all other programs that use esi (pyfa, evemon, and the excel add-in)

**Comment by Blacksmoke16** [comment] 2024-02-16 04:45
So this is actually a duplicate of #109. Which is inherently caused by https://github.com/esi/esi-issues/issues/1089. Nothing I can do directly to fix this. However, I can work around it by making GESI not require _EVERY_ scope all the time.

**Closed by Blacksmoke16** 2024-02-16 04:45 UTC
